version: '3'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_DATABASE=wp_data
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=insecure-pwd
  wordpress:
    build: wp
    ports:
      - 8080:80


      